# Author: Mamun
# All rights reserved. Copyright (c)
# docker-compose exec python python my_basic_project/app.py
# docker-compose exec python python -m pytest --cov=my_basic_project --cov-report=term-missing my_basic_project/tests/


version: '3.8'

services:
  #MySQL Service
  db:
    image: mysql:5.7
    container_name: python_news_aggregator_db
    restart: unless-stopped
    tty: true
    platform: linux/amd64
    labels:
      project: "python-news_aggregator"
      environment: local
      company: " Inc"
    environment:
      MYSQL_DATABASE: python_news_aggregator
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 33066:3306
    networks:
      - news_aggregator
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  nginx:
    image: nginx:latest
    container_name: news_aggregator_nginx
    ports:
      - 5000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - python
    networks:
      - news_aggregator

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: news_phpmyadmin
    restart: always
    ports:
      - 5010:80
    labels:
      project: "python-news_aggregator"
      environment: local
      company: " Inc"
    environment:
      UPLOAD_LIMIT: 100M
      HIDE_PHP_VERSION: 1
      PMA_HOST: db
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db
    links:
      - db
    networks:
      - news_aggregator

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_aggregator_python
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    ports:
      - "5001:5001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 5001 --reload
    networks:
      - news_aggregator
#Docker Networks
networks:
  news_aggregator:
    driver: bridge

volumes:
  dbdata:
    driver: local
